version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    ports:
      - '5430:5432'
    environment:
      LANG: 'en_US.UTF-8'
      LANGUAGE: 'en_US:en'
      LC_ALL: 'en_US.UTF-8'
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres:/var/lib/postgresql/data

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails server -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3001:3000"
    depends_on:
      - db
    env_file:
      - .env
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G

volumes:
  postgres:
