default: &default
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_DB_CONNECTIONS") { 15 } %>

local: &local
  <<: *default
  adapter: postgresql
  <% if ENV['POSTGRES_USER'].present? %>
  username: <%= ENV['POSTGRES_USER'] %>
  <% end %>
  <% if ENV['POSTGRES_PASSWORD'].present? %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  <% end %>
  <% if ENV['POSTGRES_HOST'].present? %>
  host: <%= ENV['POSTGRES_HOST'] %>
  <% end %>
  gssencmode: disable

development:
  primary:
    <<: *local
    adapter: postgresql_proxy
    database: adczar_development
  replica:
    <<: *local
    database: adczar_development
    replica: true

test:
  primary:
    <<: *local
    adapter: postgresql_proxy
    database: adczar_test
  replica:
    <<: *local
    database: adczar_test
    replica: true